beacons: [
  {
    id: aa5aab45bdcf,
    x: 1.80,
    y: 2.95,
    z: 0,
    name: A,
    modelParams: [ 61.81900587,  22.20378315 ]
  },
  {
    id: 237b44757adc,

    x: -2.5,
    y: 1.50,
    z: 0,
    name: B,
    modelParams: [ 61.81900587,  22.20378315 ]
  },
  {
    id: aaa25624c9e4,
    x: 1.85,
    y: -1.35,
    z: 0,
    name: C,
    modelParams: [ 61.81900587, 22.20378315 ]
  }
]