beacons: [
  {
    id: aa5aab45bdcf,
    x: 0.3,
    y: 0,
    z: 0,
    name: A,
    modelParams: [ 53.49079027,  24.84533631 ]
  },
  {
    id: 237b44757adc,
    x: 2.8,
    y: 0,
    z: 0,
    name: B,
    modelParams: [ 53.49079027,  24.84533631 ]
  },
  {
    id: aaa25624c9e4,
    x: 2.1,
    y: 2.91,
    z: 0,
    name: C,
    modelParams: [ 53.49079027,  24.84533631 ]
  }
]